"""Content 层：只读模组包（对应 master §4.3）。"""

from core.content.models import (
    Asset,
    Checkpoint,
    CheckOutcome,
    Condition,
    Effect,
    Entity,
    EntityKind,
    HookDef,
    InvestigatorTemplate,
    LedgerEntry,
    ModuleMeta,
    ModulePack,
    Op,
    Rule,
    RuleMode,
    SanLossSpec,
    SanTrigger,
    SanKind,
    Scene,
    SceneContent,
    StatBlock,
    VariableDef,
    WinCondition,
    World,
)
from core.content.repo import ContentRepo

__all__ = [
    "Asset",
    "Checkpoint",
    "CheckOutcome",
    "Condition",
    "Effect",
    "Entity",
    "EntityKind",
    "HookDef",
    "InvestigatorTemplate",
    "LedgerEntry",
    "ModuleMeta",
    "ModulePack",
    "Op",
    "Rule",
    "RuleMode",
    "SanLossSpec",
    "SanTrigger",
    "SanKind",
    "Scene",
    "SceneContent",
    "StatBlock",
    "VariableDef",
    "WinCondition",
    "World",
    "ContentRepo",
]
