export const ROUTES = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  HOME: '/home',
  JOIN: '/home/join',
  CREATE: '/home/create',
  MODULES: '/home/create/modules',
  MY_ROOMS: '/home/my-rooms',
  REVIEW: (roomCode: string) => `/home/my-rooms/review/${roomCode}`,
  PROFILE: '/home/profile',
  LOBBY: '/room/lobby',
  CHARACTER: '/room/character',
  CHARACTER_READY: '/room/ready',
  ROOM: '/room/play',
} as const
