"""add user_sessions, character status

Revision ID: 89a136fd4c25
Revises: 2c3dfbdb16e1
Create Date: 2026-07-13 11:38:51.941313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a136fd4c25'
down_revision: Union[str, Sequence[str], None] = '2c3dfbdb16e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.add_column('characters', sa.Column('status', sa.String(), nullable=False, server_default='complete'))
    op.create_foreign_key('fk_players_character_id', 'players', 'characters', ['character_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_players_character_id', 'players', type_='foreignkey')
    op.drop_column('characters', 'status')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
